package entities

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// Proactive nudge trigger types.
const (
	NudgeTriggerPrediction  = "prediction_triggered"
	NudgeTriggerMemory      = "memory_reminder"
	NudgeTriggerPattern     = "pattern_detected"
	NudgeTriggerMilestone   = "milestone_approaching"
	NudgeTriggerBillWarning = "bill_warning"
	NudgeTriggerIdleMoney   = "idle_money"
	NudgeTriggerIncomeEvent = "income_detected"
)

// ProactiveNudge is a push notification generated by Miriam's intelligence,
// not requiring the user to be in-app.
type ProactiveNudge struct {
	ID               uuid.UUID       `json:"id" db:"id"`
	UserID           uuid.UUID       `json:"user_id" db:"user_id"`
	TriggerType      string          `json:"trigger_type" db:"trigger_type"`
	Priority         int             `json:"priority" db:"priority"` // 1–10
	Message          string          `json:"message" db:"message"`
	ActionSuggestion json.RawMessage `json:"action_suggestion" db:"action_suggestion"`
	ExpiresAt        time.Time       `json:"expires_at" db:"expires_at"`
	DeliveredAt      *time.Time      `json:"delivered_at,omitempty" db:"delivered_at"`
	DismissedAt      *time.Time      `json:"dismissed_at,omitempty" db:"dismissed_at"`
	CreatedAt        time.Time       `json:"created_at" db:"created_at"`
}

// ProactiveNudgeSummary is the response returned to the client.
type ProactiveNudgeSummary struct {
	Nudges  []ProactiveNudge `json:"nudges"`
	Count   int              `json:"count"`
	Highest int              `json:"highest_priority"`
}
