openapi: 3.0.3
info:
  title: RAIL Advanced Features API
  description: Portfolio Analytics, Market Data, Scheduled Investments, and Rebalancing APIs
  version: 1.0.0

tags:
  - name: Analytics
    description: Portfolio performance and risk analytics
  - name: Market
    description: Real-time market data and alerts
  - name: Scheduled Investments
    description: Recurring investments and DCA
  - name: Rebalancing
    description: Portfolio rebalancing automation

paths:
  /api/v1/analytics/performance:
    get:
      tags: [Analytics]
      summary: Get portfolio performance metrics
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Performance metrics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerformanceMetrics'

  /api/v1/analytics/risk:
    get:
      tags: [Analytics]
      summary: Get portfolio risk assessment
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Risk metrics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskMetrics'

  /api/v1/analytics/diversification:
    get:
      tags: [Analytics]
      summary: Get portfolio diversification analysis
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Diversification analysis
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiversificationAnalysis'

  /api/v1/market/quote/{symbol}:
    get:
      tags: [Market]
      summary: Get real-time quote for a symbol
      parameters:
        - name: symbol
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Market quote
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketQuote'

  /api/v1/market/quotes:
    get:
      tags: [Market]
      summary: Get quotes for multiple symbols
      parameters:
        - name: symbols
          in: query
          required: true
          schema:
            type: string
          description: Comma-separated list of symbols
      responses:
        '200':
          description: Market quotes
          content:
            application/json:
              schema:
                type: object
                properties:
                  quotes:
                    type: object
                    additionalProperties:
                      $ref: '#/components/schemas/MarketQuote'

  /api/v1/market/alerts:
    get:
      tags: [Market]
      summary: Get user's market alerts
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of alerts
          content:
            application/json:
              schema:
                type: object
                properties:
                  alerts:
                    type: array
                    items:
                      $ref: '#/components/schemas/MarketAlert'
    post:
      tags: [Market]
      summary: Create a market alert
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAlertRequest'
      responses:
        '201':
          description: Alert created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketAlert'

  /api/v1/scheduled-investments:
    get:
      tags: [Scheduled Investments]
      summary: Get user's scheduled investments
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of scheduled investments
          content:
            application/json:
              schema:
                type: object
                properties:
                  scheduled_investments:
                    type: array
                    items:
                      $ref: '#/components/schemas/ScheduledInvestment'
    post:
      tags: [Scheduled Investments]
      summary: Create a scheduled investment
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateScheduledInvestmentRequest'
      responses:
        '201':
          description: Scheduled investment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduledInvestment'

  /api/v1/scheduled-investments/{id}/pause:
    post:
      tags: [Scheduled Investments]
      summary: Pause a scheduled investment
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Paused

  /api/v1/scheduled-investments/{id}/resume:
    post:
      tags: [Scheduled Investments]
      summary: Resume a paused scheduled investment
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Resumed

  /api/v1/rebalancing/configs:
    get:
      tags: [Rebalancing]
      summary: Get user's rebalancing configurations
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of configs
          content:
            application/json:
              schema:
                type: object
                properties:
                  configs:
                    type: array
                    items:
                      $ref: '#/components/schemas/RebalancingConfig'
    post:
      tags: [Rebalancing]
      summary: Create a rebalancing configuration
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRebalancingConfigRequest'
      responses:
        '201':
          description: Config created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RebalancingConfig'

  /api/v1/rebalancing/configs/{id}/plan:
    get:
      tags: [Rebalancing]
      summary: Generate rebalancing plan
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Rebalancing plan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RebalancingPlan'

  /api/v1/rebalancing/configs/{id}/execute:
    post:
      tags: [Rebalancing]
      summary: Execute rebalancing
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Rebalancing executed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  trades:
                    type: integer

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    PerformanceMetrics:
      type: object
      properties:
        total_return:
          type: string
        total_return_pct:
          type: string
        day_return:
          type: string
        day_return_pct:
          type: string
        week_return:
          type: string
        month_return:
          type: string
        year_return:
          type: string
        cagr:
          type: string
        sharpe_ratio:
          type: string
        best_day:
          type: string
        worst_day:
          type: string
        winning_days:
          type: integer
        losing_days:
          type: integer

    RiskMetrics:
      type: object
      properties:
        volatility:
          type: string
        max_drawdown:
          type: string
        max_drawdown_date:
          type: string
          format: date-time
        beta:
          type: string
        var_95:
          type: string
        risk_level:
          type: string
          enum: [low, moderate, high]

    DiversificationAnalysis:
      type: object
      properties:
        sector_allocation:
          type: object
          additionalProperties:
            type: string
        asset_type_allocation:
          type: object
          additionalProperties:
            type: string
        top_holdings:
          type: array
          items:
            $ref: '#/components/schemas/HoldingWeight'
        concentration_risk:
          type: string
        diversification_score:
          type: integer
        recommendations:
          type: array
          items:
            type: string

    HoldingWeight:
      type: object
      properties:
        symbol:
          type: string
        weight:
          type: string
        value:
          type: string
        gain_loss:
          type: string
        gain_loss_pct:
          type: string

    MarketQuote:
      type: object
      properties:
        symbol:
          type: string
        price:
          type: string
        bid:
          type: string
        ask:
          type: string
        volume:
          type: integer
        change:
          type: string
        change_pct:
          type: string
        timestamp:
          type: string
          format: date-time

    MarketAlert:
      type: object
      properties:
        id:
          type: string
          format: uuid
        symbol:
          type: string
        alert_type:
          type: string
          enum: [price_above, price_below, pct_change]
        condition_value:
          type: string
        triggered:
          type: boolean
        status:
          type: string

    CreateAlertRequest:
      type: object
      required: [symbol, alert_type, condition_value]
      properties:
        symbol:
          type: string
        alert_type:
          type: string
          enum: [price_above, price_below, pct_change]
        condition_value:
          type: number

    ScheduledInvestment:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        symbol:
          type: string
        basket_id:
          type: string
          format: uuid
        amount:
          type: string
        frequency:
          type: string
          enum: [daily, weekly, biweekly, monthly]
        next_execution_at:
          type: string
          format: date-time
        status:
          type: string
          enum: [active, paused, cancelled]
        total_invested:
          type: string
        execution_count:
          type: integer

    CreateScheduledInvestmentRequest:
      type: object
      required: [amount, frequency]
      properties:
        name:
          type: string
        symbol:
          type: string
        basket_id:
          type: string
          format: uuid
        amount:
          type: number
        frequency:
          type: string
          enum: [daily, weekly, biweekly, monthly]
        day_of_week:
          type: integer
          minimum: 0
          maximum: 6
        day_of_month:
          type: integer
          minimum: 1
          maximum: 28

    RebalancingConfig:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        target_allocations:
          type: object
          additionalProperties:
            type: string
        threshold_pct:
          type: string
        frequency:
          type: string
        status:
          type: string

    CreateRebalancingConfigRequest:
      type: object
      required: [name, allocations]
      properties:
        name:
          type: string
        allocations:
          type: object
          additionalProperties:
            type: number
        threshold_pct:
          type: number
          default: 5
        frequency:
          type: string
          enum: [manual, daily, weekly, monthly, threshold_only]

    RebalancingPlan:
      type: object
      properties:
        config_id:
          type: string
          format: uuid
        current_allocations:
          type: object
          additionalProperties:
            type: string
        target_allocations:
          type: object
          additionalProperties:
            type: string
        trades:
          type: array
          items:
            $ref: '#/components/schemas/RebalanceTradeOrder'
        total_buy_amount:
          type: string
        total_sell_amount:
          type: string

    RebalanceTradeOrder:
      type: object
      properties:
        symbol:
          type: string
        side:
          type: string
          enum: [buy, sell]
        current_pct:
          type: string
        target_pct:
          type: string
        drift_pct:
          type: string
        amount:
          type: string
        estimated_qty:
          type: string
